# Generated by Django 5.2.1 on 2025-06-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
