# Generated by Django 5.2.1 on 2025-06-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trilha_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='alunos',
        ),
    ]
