# Generated by Django 5.2.1 on 2025-06-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trilha_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='disciplina',
        ),
    ]
